mysite/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin

urlpatterns = [url(r'^i18n/', include('django.conf.urls.i18n')), ]  # Language redirect

urlpatterns += i18n_patterns(
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^polls/', include('polls.urls')),
)

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    # ex: /polls/tests
    url(r'^tests/$', views.tests, name='tests'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class Question(models.Model):
    """
        Sotres a question with severals :model:`polls.Choice`
    """
    question_text = models.CharField(verbose_name=_('question text'), max_length=200, help_text=_("I'm a help text"))
    pub_date = models.DateTimeField(_('date published'))

    def was_published_recently(self):
        """
        Sets if was published in the last day
        :return:
        """
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = _('Published recently?')
    was_published_recently.alters_data = False  # Use when True applies

    def __str__(self):
        return self.question_text

    class Meta:
        verbose_name = _('question')
        verbose_name_plural = _('questions')


class Choice(models.Model):
    """
        Represents a possible aswer for a :model:`poll.Question` and their votes
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(_("option"), max_length=200)
    votes = models.IntegerField(_("votes"), default=0)

    def __str__(self):
        return self.choice_text

    class Meta:
        verbose_name = _('choice')
        verbose_name_plural = _('choices')

polls/views.py
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.views import generic

from polls.models import Question, Choice


class IndexView(generic.ListView):
    """
       Display all :model:`polls.Questions`.

       **Context**

       ``polls``
           latests_question_list

       **Template:**

       :template:`polls/index.html`
       """
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    """
       Detalled view of a :model:`polls.Questions`.

       **Context**

       ``polls``
           question

       **Template:**

       :template:`polls/detail.html`
       """
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    """
       Votes for a :model:`polls.Choice`.

       **Context**

       ``polls``
           question
           error_message

       **Template:**

       :template:`polls/detail.html`
       """
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        data = {
            'question': question,
            # Translators: Error when POSt and not aption selected
            'error_message': _("You didn't select a choice."),
        }

        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', data)

    else:
        selected_choice.votes = F('votes') + 1  # F -> No race condition
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


# text = ungettext(
#     'There is %(count)d %(name)s available.',
#     'There are %(count)d %(name)s available.',
#     count
# ) % {
#     'count': count,
#     'name': name
# }


def tests(request):
    """
       View to make tests with templates


       **Template:**

       :template:`polls/tests.html`
       """
    # template = get_template('polls/tests.html')

    c = {
        "title": _("tests"),
        "second": "second",
        "tt": request,
    }

    return render(request, 'polls/tests.html', c)

polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Question #{{ question.id }}</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
    {% endfor %}
    <input type="submit" value="Vote"/>
</form>
</body>
</html>

polls/templates/polls/index.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% trans "This is the title." %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}"/>
</head>
<body>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

polls/templates/polls/tests.html
{% load i18n %}
{% load humanize %}

{% get_current_language as LANGUAGE_CODE %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    {# Capitalize the string #}
    <title>{{ title|title }}</title>
</head>
<body>
<h1>{% trans "Still works:" context "Main test page" %} {% now "jS F Y H:i" as date %} </h1>
{% lorem 2 p %}
<p> {{ get_language_info_list|pprint }} </p>

{% url 'polls:tests' as the_url %}
{% blocktrans trimmed %}
    This is a URL: {{ the_url }}
{% endblocktrans %}

<form action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <input name="next" type="hidden" value="{{ redirect_to }}"/>
    <select name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_translated }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
    <input type="submit" value="Go"/>
</form>

<h2>Localization:</h2>
<p>{{ "1000000000.2"|intcomma }}</p>

</body>
</html>